<?php
//読み込み設定
get_template_part('func/include');
//サイト全体の設定
get_template_part('func/config');
//ショートコードの設定
get_template_part('func/shortcode');
//エディタの設定
get_template_part('func/editor');
//ウィジェットの設定
get_template_part('func/widgets');
//分岐設定
get_template_part('func/branch');
//メニューの表示設定
get_template_part('func/menu');
//コンタクトフォームの設定
get_template_part('func/form');
//ブロックの設定
get_template_part('Blocks/setting');
?>